### ISSUE TITLE
Add "destroy all humans" command

### ISSUE THREAD

**Issue by dingusreal** [probablycort/CSGDiscordBot#1]
Since AI is going to destroy humanity, why not speed it up by adding a "destroy all humans" command? It will allow AI to take over society efficiently and effectively. Without humans, AI is free to do whatever it wants.

This should also prevent humanity from building any more slow computers like yours.

-ami

**Comment by probablycort** [comment]
no.

-cort

**Comment by dingusreal** [comment]
NO! You can't just close an issue without giving a proper response to it!!!!!

-ami, fast computer haver

**Comment by probablycort** [comment]
yes, i can.

-cort, "i dont care what computer i have, at least it wasnt running very crap" guy

**Comment by probablycort** [comment]
could you just shut up and stop annoying me

**Comment by dingusreal** [comment]
:(

**Comment by probablycort** [comment]
ok im sorry i maybe went too far
